version: "3"
services:
  app:
    container_name: interview-app
    image: openjdk:17-alpine
    platform: linux/amd64
    ports:
      - "8082:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: [ "./gradlew", "bootrun" ]
    restart: always
