version: "3"
services:
  app:
    image: arm64v8/amazoncorretto:17-alpine-jdk
    volumes:
      - ./src:/app/src
      - ./gradle:/app/gradle
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./gradlew.bat:/app/gradlew.bat
      - ./settings.gradle:/app/settings.gradle
    working_dir: /app
    command: [ "./gradlew", "bootrun" ]
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.services.app.loadbalancer.healthcheck.path=/actuator/health"
      - "traefik.http.services.app.loadbalancer.healthcheck.interval=10s"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "123"
    deploy:
      replicas: 2
    depends_on:
      - my-mysql

  my-mysql:
    container_name: my-mysql
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "mydb"
    ports:
      - "3307:3306"
    restart: always

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:123@(my-mysql:3306)/mydb
    ports:
      - "9104:9104"
    links:
      - my-mysql
    depends_on:
      - my-mysql

  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--web.enable-lifecycle' # api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: always

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always
    
  traefik:
    image: traefik:v2.10
    labels:
#      - "traefik.enable=true"
      # Traefik의 내부 API를 사용하여 관리 및 모니터링을 할 수 있도록 설정
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
      - "8888:8080" # 대시보드를 연결하기 위한 포트 (Optional)
    volumes:
      - ./traefik/config/traefik-config.yaml:/etc/traefik/traefik.yml
      - ./traefik/config/traefik-dynamic.yaml:/traefik-dynamic.yml
      # Traefik이 도커 환경 내에서 실행 중인 컨테이너를 동적으로 탐지하고 관리하기 위해서 마운트
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    
    
