version: "3"
services:
#  app:
#    container_name: app
#    image: arm64v8/amazoncorretto:17-alpine-jdk
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./src:/app/src
#      - ./gradle:/app/gradle
#      - ./build.gradle:/app/build.gradle
#      - ./gradlew:/app/gradlew
#      - ./gradlew.bat:/app/gradlew.bat
#      - ./settings.gradle:/app/settings.gradle
#    working_dir: /app
#    command: [ "./gradlew", "bootrun" ]
#    restart: always
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.6
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
#    depends_on:
#      - app
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.7
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
    
  
