spring:
  application:
    name: interview_app
  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  data:
    redis:
      host: redis
      port: 6380

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name} # 서비스 단위의 식별자. Prometheus label에 추가됨
