spring:
  application:
    name: interview_app
    
server:
  tomcat:
    connection-timeout: 5000
    max-threads: 10

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name} # 서비스 단위의 식별자. Prometheus label에 추가됨